/* 首页入口常量
 * @Descripttion: 
 * @version: 
 * @Author: xiaowe
 * @Date: 2019-7-15 16:37:44
 * @LastEditors: xiaowe
 * @LastEditTime: 2019-7-15 16:37:40
 */

/**
 * 快递公司配置
 */
export let expressCompanyData = {
    '1':{src: require('../../../../../assets/img/expressServer/company/icon_companytype1.png'), name: '顺丰快递', needVerifyPhoneNo:true,ishiden:false},
    '2':{src: require('../../../../../assets/img/expressServer/company/icon_companytype2.png'), name: '圆通快递', needVerifyPhoneNo:false,ishiden:false},
    '3':{src: '', name: '快递100', needVerifyPhoneNo:false,ishiden:true},
}

/**
 * 入口配置文件
 */
export let expressListData = [
    {src: require('../../../../../assets/img/expressServer/bg_express_shangmen@2x.png'), name: '上门取件',tips:'便捷、快速', url: '/order/confirm', type:'route', isOpen:true},
    {src: require('../../../../../assets/img/expressServer/bg_express_tongcheng@2x.png'), name: '同城急送',tips:'高效、快速', url: '', type:'route', isOpen:false}, 
]

/**
 * 快递订单状态
 * @text 订单状态描述
 * @detailText 订单状态物流描述
 * @listClass 列表页状态按钮样式
 * @orderTypeClass 订单详情页面订单状态样式
 * @detailType 订单type用于订单详情页面暂时不同内容
 * @showCancel 订单详情页面是否展示取消按钮
 * @showReBut 订单详情页面是否展示再次预订按钮
 * @isCancel 列表页用于控制取消状态的样式
 * @expressListShow 列表页用于控制是否显示物流信息
 * 
 * 
 */
export let orderTypeMap = {
    'WAIT_TO_ACCEPT':{
        text: '待快递员接单', 
        detailText:'待快递员接单',
        listClass:'orange',
        orderTypeClass: 'type1', 
        detailType:'waitToAccept',
        showCancel:true,
        showReBut:false,
        expressListShow:false,
    },
    'ACCEPT':{
        text: '已接单，待揽件', 
        detailText:'已接单，待揽件',
        listClass:'orange', 
        orderTypeClass: 'type2', 
        detailType:'accept', 
        showCancel:true,
        showReBut:false,
        expressListShow:false,
    }, 
    'NOT_SEND':{
        text: '已取消', 
        detailText:'快递员调度失败，订单已取消',
        listClass:'gray', 
        orderTypeClass: 'type4', 
        detailType:'cancel', 
        showCancel:false,
        showReBut:true,
        expressListShow:false,
    },
    'GOT':{
        text: '已揽件', 
        detailText:'物流信息',
        listClass:'blue', 
        orderTypeClass: 'type3', 
        detailType:'tranSporting', 
        showCancel:false,
        showReBut:false,
        expressListShow:true,
    }, 
    'TRANSPORTING':{
        text: '运输中', 
        detailText:'物流信息',
        listClass:'blue', 
        orderTypeClass: 'type3', 
        detailType:'tranSporting', 
        showCancel:false,
        showReBut:false,
        expressListShow:true,
    }, 
    'SENT_SCAN':{
        text: '派件中', 
        detailText:'物流信息',
        listClass:'blue', 
        orderTypeClass: 'type3', 
        detailType:'tranSporting',
        showCancel:false,
        showReBut:false,
        expressListShow:true,
    },
    'SIGNED':{
        text: '已签收', 
        detailText:'物流信息',
        listClass:'black', 
        orderTypeClass: 'type3', 
        detailType:'tranSporting',
        showCancel:false,
        showReBut:false,
        expressListShow:true,
    },
    'CANCELLED':{
        text: '已取消', 
        detailText:'订单已取消',
        listClass:'gray', 
        orderTypeClass: 'type4', 
        detailType:'cancel', 
        showCancel:false,
        showReBut:true,
        expressListShow:false,
    }, 
}
/**
 * 物流详情状态
 */
export let expressTypeList = [
    {text: '已揽件', type:'GOT', iconClass: 'iconOne'},
    {text: '运输中', type:'TRANSPORTING', iconClass: 'iconTwo'}, 
    {text: '派件中', type:'SENT_SCAN', iconClass: 'iconThree'},
    {text: '已签收', type:'SIGNED', iconClass: 'iconFour'} 

]
/**
 * 物流详情状态
 */
export let expressTypeMap = {
    'GOT':{text: '已揽件', typeClass: 'typeOne',canContact:false},
    'TRANSPORTING':{text: '运输中', typeClass: 'typeTwo',canContact:false}, 
    'SENT_SCAN':{text: '派件中', typeClass: 'typeThree',canContact:true},
    'SIGNED':{text: '已签收', typeClass: 'typeFour',canContact:false}, 
}
/**
 * 快递物品分类
 */
export let expressCargoData = ['文件','数码产品','生活用品','食品','服饰','其他'];

/**
 * 快递物品分类
 */
export let sendTimeData = [
    {
        'name':'今天',
        'list':[
            {start: '',end:'', text: '两小时上门','isNear':true,id:-1},
            {start: '09:00',end:'11:00', text: '09:00-11:00',id:9},
            {start: '11:00',end:'13:00', text: '11:00-13:00',id:11},
            {start: '13:00',end:'15:00', text: '13:00-15:00',id:13},
            {start: '15:00',end:'17:00', text: '15:00-17:00',id:15},
            {start: '17:00',end:'19:00', text: '17:00-19:00',id:17}
        ]
    },
    {
        'name':'明天',
        'list':[
            {start: '09:00',end:'11:00', text: '09:00-11:00',id:109},
            {start: '11:00',end:'13:00', text: '11:00-13:00',id:111},
            {start: '13:00',end:'15:00', text: '13:00-15:00',id:113},
            {start: '15:00',end:'17:00', text: '15:00-17:00',id:115},
            {start: '17:00',end:'19:00', text: '17:00-19:00',id:117}
        ]
    },
    {
        'name':'后天',
        'list':[
            {start: '09:00',end:'11:00', text: '09:00-11:00',id:209},
            {start: '11:00',end:'13:00', text: '11:00-13:00',id:211},
            {start: '13:00',end:'15:00', text: '13:00-15:00',id:213},
            {start: '15:00',end:'17:00', text: '15:00-17:00',id:215},
            {start: '17:00',end:'19:00', text: '17:00-19:00',id:217}
        ]
    }
]

/**
 * 快递100所包含的快递公司
 */
export let outExpressCompanyData = {
    "yunda":"韵达快递",
    "youzhengguonei":"邮政快递包裹",
    "zhongtong":"中通快递",
    "yuantong":"圆通速递",
    "huitongkuaidi":"百世快递",
    "shunfeng":"顺丰速运",
    "shentong":"申通快递",
    "jd":"京东物流",
    "ems":"EMS",
    "tiantian":"天天快递",
    "debangwuliu":"德邦",
    "zhaijisong":"宅急送",
    "youshuwuliu":"优速快递",
    "debangkuaidi":"德邦快递",
    "baishiwuliu":"百世快运",
    "pjbest":"品骏快递",
    "transrush":"TransRush",
    "dhl":"DHL-中国件",
    "zhongtongkuaiyun":"中通快运",
    "suning":"苏宁物流",
    "annengwuliu":"安能快运",
    "suer":"速尔快递",
    "yundakuaiyun":"韵达快运",
    "usps":"USPS",
    "adapost":"安达速递",
    "upsen":"UPS-全球件",
    "jinguangsudikuaijian":"京广速递",
    "ewe":"EWE全球快递",
    "youzhengbk":"邮政标准快递",
    "danniao":"丹鸟",
    "emsguoji":"EMS-国际件",
    "tnt":"TNT",
    "fedex":"FedEx-国际件",
    "sfwl":"盛丰物流",
    "quanfengkuaidi":"全峰快递",
    "zhuanyunsifang":"转运四方",
    "yuantongkuaiyun":"圆通快运",
    "subida":"速必达",
    "dhlen":"DHL-全球件",
    "jiuyescm":"九曳供应链",
    "japanposten":"日本（Japan Post）",
    "jym56":"加运美速递",
    "auexpress":"澳邮中国快运",
    "kuayue":"跨越速运",
    "youzhengguoji":"国际包裹",
    "zhimakaimen":"芝麻开门",
    "guotongkuaidi":"国通快递",
    "farlogistis":"泛远国际物流",
    "zlxdjwl":"中粮鲜到家物流",
    "lianbangkuaidi":"联邦快递",
    "zhongtongguoji":"中通国际",
    "yimidida":"壹米滴答",
    "lianhaowuliu":"联昊通",
    "yuxinwuliu":"宇鑫物流",
    "rrs":"日日顺物流",
    "dsukuaidi":"D速快递",
    "btexpress":"邦泰快运",
    "annto":"安得物流",
    "gslhkd":"联合快递",
    "longbanwuliu":"龙邦速递",
    "wjkwl":"万家康物流",
    "ups":"UPS",
    "emsbg":"EMS包裹",
    "wherexpess":"威盛快递",
    "yafengsudi":"亚风速递",
    "flyway":"程光快递",
    "ontrac":"OnTrac",
    "arkexpress":"方舟速递",
    "meiquick":"美快国际物流",
    "ftd":"富腾达国际货运",
    "weitepai":"微特派",
    "wanxiangwuliu":"万象物流",
    "superb":"Superb Grace",
    "zhongsukuaidi":"中速快递",
    "synship":"SYNSHIP快递",
    "tiandihuayu":"天地华宇",
    "lntjs":"特急送",
    "jiayunmeiwuliu":"加运美",
    "canpost":"加拿大(Canada Post)",
    "banma":"斑马物流",
    "coe":"COE",
    "rlgaus":"澳洲飞跃物流",
    "cncexp":"C&C国际速递",
    "astexpress":"安世通快递",
    "yangbaoguo":"洋包裹",
    "yuntrack":"YUN TRACK",
    "valueway":"美通",
    "jiajiwuliu":"佳吉快运",
    "xlobo":"Xlobo贝海国际",
    "shpost":"同城快寄",
    "ocs":"OCS",
    "fedexus":"FedEx-美国件",
    "dpd":"DPD",
    "chnexp":"中翼国际物流",
    "xinfengwuliu":"信丰物流",
    "ubonex":"优邦速运",
    "blueskyexpress":"蓝天快递",
    "buytong":"百通物流",
    "guangdongyouzhengwuliu":"广东邮政",
    "dhlde":"DHL-德国件（DHL Deutschland）",
    "cosco":"中远e环球",
    "bpost":"比利时（Bpost）",
    "changjiang":"长江国际速递",
    "zhaijibian":"宅急便",
    "ctoexp":"泰国中通CTO",
    "polarexpress":"极地快递",
    "sunjex":"新杰物流",
    "xdexpress":"迅达速递",
    "aramex":"Aramex",
    "meixi":"美西快递",
    "pfcexpress":"皇家物流",
    "nsf":"新顺丰（NSF）",
    "auspost":"澳大利亚(Australia Post)",
    "youban":"邮邦国际",
    "ytchengnuoda":"承诺达",
    "epanex":"泛捷国际速递",
    "huangmajia":"黄马甲",
    "sxjdfreight":"顺心捷达",
    "dindon":"叮咚澳洲转运",
    "huanqiu":"环球速运",
    "bulgarian":"保加利亚（Bulgarian Posts）",
    "hkpost":"中国香港(HongKong Post)",
    "euasia":"欧亚专线",
    "tnten":"TNT-全球件",
    "crazyexpress":"疯狂快递",
    "anxl":"安迅物流",
    "zjstky":"苏通快运",
    "kuaijiesudi":"快捷速递",
    "baishiyp":"百世云配",
    "emsen":"EMS-英文",
    "esinotrans":"中外运",
    "lianbangkuaidien":"联邦快递-英文",
    "idamalu":"大马鹿",
    "tmwexpress":"明达国际速递",
    "wtdchina":"威时沛运货运",
    "gxwl":"光线速递",
    "bazirim":"皮牙子快递",
    "emsinten":"EMS-国际件-英文",
    "tntuk":"TNT UK",
    "qexpress":"易达通快递",
    "sdto":"速达通",
    "ueq":"UEQ快递",
    "jingshun":"景顺物流",
    "yuntongkuaidi":"运通中港",
    "nanjingshengbang":"晟邦物流",
    "zhonghuan":"中环快递",
    "chunghwa56":"中骅物流",
    "hengluwuliu":"恒路物流",
    "ztky":"中铁快运",
    "westwing":"西翼物流",
    "lijisong":"成都立即送",
    "exfresh":"安鲜达",
    "gdkd":"港快速递",
    "bsht":"百事亨通",
    "shenghuiwuliu":"盛辉物流",
    "royalmail":"英国小包（Royal Mail）",
    "quanyikuaidi":"全一快递",
    "sxexpress":"三象速递",
    "tstexp":"TST速运通",
    "ndwl":"南方传媒物流",
    "aotsd":"澳天速运",
    "ane66":"安能快递",
    "lbex":"龙邦物流",
    "swisspostcn":"瑞士邮政",
    "youyou":"优优速递",
    "unitedex":"联合速运",
    "rufengda":"如风达",
    "dpex":"DPEX",
    "zhongyouwuliu":"中邮物流",
    "sundarexpress":"顺达快递",
    "spring56":"春风物流",
    "auod":"澳德物流",
    "dpduk":"DPD UK",
    "ucs":"合众速递(UCS）",
    "jiayiwuliu":"佳怡物流",
    "hermes":"Hermes",
    "fedexcn":"Fedex-国际件-中文",
    "huanqiuabc":"中国香港环球快运",
    "singpost":"新加坡小包(Singapore Post)",
    "sut56":"速通物流",
    "ycgky":"远成快运",
    "edtexpress":"e直运",
    "chengguangkuaidi":"程光快递",
    "chukou1":"出口易",
    "zhongtiewuliu":"中铁物流",
    "ecmscn":"易客满",
    "cnpex":"CNPEX中邮快递",
    "httx56":"汇通天下物流",
    "uluckex":"优联吉运",
    "yousutongda":"优速通达",
    "mmlogi":"猛犸速递",
    "postnl":"荷兰邮政(PostNL international registered mail)",
    "topspeedex":"中运全速",
    "kerrytj":"嘉里大荣物流",
    "jialidatong":"嘉里大通",
    "fastgo":"速派快递(FastGo)",
    "homecourier":"如家国际快递",
    "shipgce":"飞洋快递",
    "aae":"AAE-中国件",
    "sendtochina":"速递中国",
    "dpexen":"Toll",
    "hrex":"锦程快递",
    "wanjiawuliu":"万家物流",
    "yue777":"玥玛速运",
    "efs":"EFS Post（平安快递）",
    "guexp":"全联速运",
    "hgy56":"环国运物流",
    "disifang":"递四方",
    "datianwuliu":"大田物流",
    "yuntong":"运通速运",
    "jieanda":"捷安达",
    "hnht56":"鸿泰物流",
    "zhongtongphone":"中通（带电话）",
    "stoexpress":"美国申通",
    "xiyoug":"西游寄",
    "parcelforce":"英国大包、EMS（Parcel Force）",
    "uschuaxia":"华夏国际速递",
    "gooday365":"日日顺智慧物联",
    "newsway":"家家通快递",
    "runhengfeng":"全时速运",
    "pingandatengfei":"平安达腾飞",
    "zhongchuan":"众川国际",
    "fastgoexpress":"速派快递",
    "xunsuexpress":"迅速快递",
    "excocotree":"可可树美中速运",
    "yingchao":"英超物流",
    "tntau":"TNT Australia",
    "shd56":"商海德物流",
    "shengfengwuliu":"盛丰物流",
    "yw56":"燕文物流",
    "chinaicip":"卓志速运",
    "sccod":"丰程物流",
    "yuanchengwuliu":"远成物流",
    "tykd":"天翼快递",
    "stoe56":"申通快运",
    "deutschepost":"德国(Deutsche Post)",
    "yuananda":"源安达",
    "iyoungspeed":"驿扬国际速运",
    "csuivi":"法国(La Poste)",
    "shangcheng":"尚橙物流",
    "royalmailcn":"英国邮政小包",
    "sutongwuliu":"速通物流",
    "koreapost":"韩国（Korea Post）",
    "hd":"宏递快运",
    "italiane":"意大利(Poste Italiane)",
    "japanpost":"日本郵便",
    "shangqiao56":"商桥物流",
    "yaofeikuaidi":"耀飞同城快递",
    "kingfreight":"货运皇",
    "fyex":"飞云快递系统",
    "qbexpress":"秦邦快运",
    "jgwl":"景光物流",
    "cpsair":"华中快递",
    "postnlcn":"荷兰邮政-中文(PostNL international registered mail)",
    "koreapostcn":"韩国邮政",
    "newzealand":"新西兰（New Zealand Post）",
    "koalaexp":"考拉速递",
    "cccc58":"中集冷云",
    "lineone":"一号线",
    "citylink":"City-Link",
    "hyytes":"恒宇运通",
    "tywl99":"天翼物流",
    "yuantongguoji":"圆通国际",
    "shunfengen":"顺丰-美国件",
    "anxindakuaixi":"安信达",
    "jiazhoumao":"加州猫速递",
    "dechuangwuliu":"深圳德创物流",
    "lantiankuaidi":"蓝天快递",
    "fbkd":"飞邦快递",
    "xynyc":"新元国际",
    "jcsuda":"嘉诚速达",
    "handboy":"汉邦国际速递",
    "haidaibao":"海带宝",
    "qinyuan":"秦远物流",
    "macao":"中国澳门(Macau Post)",
    "meiguokuaidi":"美国快递",
    "la911":"鼎润物流",
    "tianma":"天马迅达",
    "nebuex":"星云速递",
    "uscbexpress":"易境达国际物流",
    "saiaodimmb":"赛澳递for买卖宝",
    "efspost":"EFSPOST",
    "chszhonghuanguoji":"CHS中环国际快递",
    "lasership":"LaserShip",
    "oneexpress":"一速递",
    "colissimo":"法国小包（colissimo）",
    "onehcang":"一号仓",
    "ausexpress":"澳世速递",
    "zteexpress":"ZTE中兴物流",
    "luben":"陆本速递 LUBEN EXPRESS",
    "wlwex":"星空国际",
    "correosdees":"西班牙(Correos de Espa?a)",
    "stosolution":"申通国际",
    "nederlandpost":"荷兰速递(Nederland Post)",
    "sunspeedy":"新速航",
    "zyzoom":"增速跨境 ",
    "yidatong":"易达通",
    "jinan":"金岸物流",
    "beebird":"锋鸟物流",
    "nuoyaao":"偌亚奥国际快递",
    "sagawa":"佐川急便",
    "trakpak":"TRAKPAK",
    "anjiekuaidi":"青岛安捷快递",
    "ruidianyouzheng":"瑞典（Sweden Post）",
    "jiujiuwl":"久久物流",
    "uhi":"优海国际速递",
    "postserv":"台湾（中华邮政）",
    "tcxbthai":"TCXB国际物流",
    "dongjun":"成都东骏物流",
    "baitengwuliu":"百腾物流",
    "malaysiapost":"马来西亚小包（Malaysia Post(Registered)）",
    "yyqc56":"一运全成物流",
    "tzky":"铁中快运",
    "changwooair":"昌宇国际",
    "hangrui":"上海航瑞货运",
    "ht22":"海淘物流",
    "yzswuliu":"亚洲顺物流",
    "ganzhongnengda":"能达速递",
    "zhonghuanus":"中环转运",
    "minghangkuaidi":"民航快递",
    "taijin":"泰进物流",
    "jiacheng":"佳成快递 ",
    "swisspost":"瑞士(Swiss Post)",
    "tcat":"黑猫宅急便",
    "bee001":"蜜蜂速递",
    "baifudongfang":"百福东方",
    "zengyisudi":"增益速递",
    "shunfenghk":"顺丰-繁体",
    "1ziton":"一智通",
    "bangsongwuliu":"邦送物流",
    "ftky365":"丰通快运",
    "whgjkd":"香港伟豪国际物流",
    "emswuliu":"EMS物流",
    "abcglobal":"全球快运",
    "suteng":"广东速腾物流",
    "parcelforcecn":"英国邮政大包EMS",
    "qichen":"启辰国际速递",
    "wuliuky":"五六快运",
    "dhlbenelux":"DHL Benelux",
    "anposten":"爱尔兰(An Post)",
    "etong":"E通速递",
    "landmarkglobal":"Landmark Global",
    "aliexpress":"无忧物流",
    "yodel":"YODEL",
    "freakyquick":"FQ狂派速递",
    "hac56":"瀚朝物流",
    "nell":"尼尔快递",
    "szyouzheng":"深圳邮政",
    "jxfex":"集先锋快递",
    "newgistics":"Newgistics",
    "bdatong":"八达通",
    "bpostinter":"比利时国际(Bpost international)",
    "yongchangwuliu":"永昌物流",
    "yujiawl":"宇佳物流",
    "bosind":"堡昕德速递",
    "iparcel":"UPS i-parcel",
    "pochta":"俄罗斯邮政(Russian Post)",
    "myhermes":"MyHermes",
    "ytkd":"运通中港快递",
    "wondersyd":"中邮速递",
    "heimao56":"黑猫速运",
    "hkposten":"中国香港(HongKong Post)英文",
    "airpak":"airpak expresss",
    "asendiausa":"Asendia USA",
    "haihongwangsong":"海红网送",
    "sxhongmajia":"红马甲物流",
    "chronopostfra":"法国大包、EMS-法文（Chronopost France）",
    "sd138":"泰国138国际物流",
    "taoplus":"淘布斯国际物流",
    "india":"印度(India Post)",
    "signedexpress":"签收快递",
    "a2u":"A2U速递",
    "cnausu":"中澳速递",
    "boyol":"贝业物流",
    "cht361":"诚和通",
    "duodao56":"duodao56",
    "wandougongzhu":"豌豆物流",
    "cex":"城铁速递",
    "easyexpress":"EASY EXPRESS",
    "hltop":"海联快递",
    "khzto":"柬埔寨中通",
    "cnair":"CNAIR",
    "yiouzhou":"易欧洲国际物流",
    "stkd":"顺通快递",
    "ltx":"蓝天国际快递",
    "thailand":"泰国（Thailand Thai Post）",
    "xtb":"鑫通宝物流",
    "zsmhwl":"明辉物流",
    "anjie88":"安捷物流",
    "doortodoor":"CJ物流",
    "speedpost":"新加坡EMS、大包(Singapore Speedpost)",
    "yundaexus":"美国云达",
    "dekuncn":"德坤物流",
    "kejie":"科捷物流",
    "cnws":"中国翼",
    "ecotransite":"东西E全运",
    "feibaokuaidi":"飞豹快递",
    "jetexpressgroup":"澳速通国际速递",
    "nntengda":"腾达速递",
    "quanjitong":"全际通",
    "uszcn":"转运中国",
    "maxeedexpress":"澳洲迈速快递",
    "advancing":"安达信",
    "goldjet":"高捷快运",
    "pengyuanexpress":"鹏远国际速递",
    "chengpei":"河北橙配",
    "portugalctt":"葡萄牙（Portugal CTT）",
    "yiqisong":"一起送",
    "quanritongkuaidi":"全日通",
    "adlerlogi":"德国雄鹰速递",
    "bangbangpost":"帮帮发",
    "fastway":"Fastway Ireland",
    "chunfai":"中国香港骏辉物流",
    "guoeryue":"天天快物流",
    "trackparcel":"track-parcel",
    "ynztsy":"纵通速运",
    "zhongtianwanyun":"中天万运",
    "chuanxiwuliu":"传喜物流",
    "cllexpress":"澳通华人物流",
    "fanyukuaidi":"凡宇快递",
    "georgianpost":"格鲁吉亚(Georgian Pos）",
    "tmg":"株式会社T.M.G",
    "postnlpacle":"荷兰包裹(PostNL International Parcels)",
    "beckygo":"佰麒快递",
    "gslexpress":"德尚国际速递",
    "hlyex":"好来运",
    "quansu":"全速物流",
    "quantwl":"全通快运",
    "ukrpostcn":"乌克兰邮政包裹",
    "wto56kj":"温通物流",
    "abf":"ABF",
    "alog":"心怡物流",
    "comexpress":"邦通国际",
    "dayangwuliu":"大洋物流",
    "pcaexpress":"PCA Express",
    "bjemstckj":"北京EMS",
    "cevalogistics":"CEVA Logistic",
    "szuem":"联运通物流",
    "wowvip":"沃埃家",
    "latvia":"拉脱维亚(Latvijas Pasts)",
    "nzzto":"新西兰中通",
    "onway":"昂威物流",
    "adaexpress":"明大快递",
    "dhlecommerce":"dhl小包",
    "feiyuanvipshop":"飞远配送",
    "kjde":"跨境直邮通",
    "posta":"坦桑尼亚（Tanzania Posts Corporation）",
    "thaizto":"泰国中通ZTO",
    "finland":"芬兰(Itella Posti Oy)",
    "jdiex":"JDIEX",
    "mchy":"木春货运",
    "ydglobe":"云达通",
    "zsda56":"转瞬达集运",
    "zsky123":"准实快运",
    "canpostfr":"加拿大邮政",
    "santaisudi":"三态速递",
    "ztjieda":"泰捷达国际物流",
    "austria":"奥地利(Austrian Post)",
    "belgiumpost":"比利时(Belgium Post)",
    "fox":"FOX国际快递",
    "nalexpress":"新亚物流",
    "ptt":"土耳其",
    "shenganwuliu":"圣安物流",
    "shunjiefengda":"顺捷丰达",
    "yunfeng56":"韵丰物流",
    "huaqikuaiyun":"华企快运",
    "ireland":"爱尔兰(An Post)",
    "ltexp":"乐天速递",
    "vps":"维普恩物流",
    "wykjt":"51跨境通",
    "xinning":"新宁物流",
    "auvanda":"中联速递",
    "bqcwl":"百千诚物流",
    "brazilposten":"巴西(Brazil Post/Correios)",
    "ceskaposta":"捷克（?eská po?ta）",
    "correo":"乌拉圭（Correo Uruguayo）",
    "dadaoex":"大道物流",
    "dcs":"DCS",
    "jieborne":"捷邦物流",
    "jixianda":"急先达",
    "mingliangwuliu":"明亮物流",
    "qesd":"7E速递",
    "shunjieda":"顺捷达",
    "wanboex":"万博快递",
    "yuefengwuliu":"越丰物流",
    "eucpost":"德国 EUC POST",
    "feikangda":"飞康达",
    "hexinexpress":"合心速递",
    "junfengguoji":"骏丰国际速递",
    "malaysiaems":"马来西亚大包、EMS（Malaysia Post(parcel,EMS)）",
    "postnlchina":"荷兰邮政-中国件",
    "serbia":"塞尔维亚(PE Post of Serbia)",
    "shangda":"上大物流",
    "uzbekistan":"乌兹别克斯坦(Post of Uzbekistan)",
    "ahdf":"德方物流",
    "auvexpress":"AUV国际快递",
    "baotongkd":"宝通快递",
    "cameroon":"喀麦隆(CAMPOST)",
    "cces":"CCES/国通快递",
    "fastontime":"加拿大联通快运",
    "hjs":"猴急送",
    "parcelchina":"诚一物流",
    "saudipost":"沙特阿拉伯(Saudi Post)",
    "szdpex":"深圳DPEX",
    "tnjex":"明通国际快递",
    "xianglongyuntong":"祥龙运通物流",
    "anlexpress":"新干线快递",
    "benteng":"奔腾物流",
    "chengtong":"城通物流",
    "cloudexpress":"CE易欧通国际速递",
    "didasuyun":"递达速运",
    "eta100":"易达国际速递",
    "europeanecom":"europeanecom",
    "exsuda":"E速达",
    "gongsuda":"共速达",
    "hungary":"匈牙利（Magyar Posta）",
    "jcex":"jcex",
    "jdexpressusa":"骏达快递",
    "kuaidawuliu":"快达物流",
    "ldxpres":"林道国际快递-英文",
    "minbangsudi":"民邦速递",
    "scic":"中加国际快递",
    "southafrican":"南非（South African Post Office）",
    "yinjiesudi":"银捷速递",
    "zjgj56":"振捷国际货运",
    "amcnorder":"amazon-国内订单",
    "aolau":"AOL澳通速递",
    "chinapostcb":"中邮电商",
    "chinasqk":"SQK国际速递",
    "emms":"澳州顺风快递",
    "ghtexpress":"GHT物流",
    "hongywl":"红远物流",
    "iceland":"冰岛(Iceland Post)",
    "jixiangyouau":"吉祥邮（澳洲）",
    "kfwnet":"快服务",
    "logistics":"華信物流WTO",
    "lsexpress":"6LS EXPRESS",
    "lutong":"鲁通快运",
    "luxembourg":"卢森堡(Luxembourg Post)",
    "republic":"叙利亚(Syrian Post)",
    "savor":"海信物流",
    "shlexp":"SHL畅灵国际物流",
    "shlindao":"林道国际快递",
    "uexiex":"欧洲UEX",
    "vangenexpress":"万庚国际速递",
    "vnpost":"越南EMS(VNPost Express)",
    "yitongda":"易通达",
    "ajexpress":"捷记方舟",
    "albania":"阿尔巴尼亚(Posta shqipatre)",
    "bht":"BHT",
    "biaojikuaidi":"彪记快递",
    "ccd":"河南次晨达",
    "chuangyi":"创一快递",
    "emonitoring":"波兰小包(Poczta Polska)",
    "euguoji":"易邮国际",
    "feikuaida":"飞快达",
    "fsexp":"全速快递",
    "hotwms":"皇家云仓",
    "htongexpress":"华通快运",
    "jiajikuaidi":"佳吉快递",
    "jindawuliu":"金大物流",
    "ksudi":"快速递",
    "kuai8":"快8速运",
    "postelbe":"PostElbe",
    "riyuwuliu":"日昱物流",
    "rrskx":"日日顺快线",
    "rrthk":"日日通国际",
    "slovenia":"斯洛文尼亚(Slovenia Post)",
    "uspscn":"USPSCN",
    "vancl":"凡客配送（作废）",
    "xipost":"西邮寄",
    "yibangwuliu":"一邦速递",
    "yiex":"宜送物流",
    "yizhengdasuyun":"一正达速运",
    "yunexpress":"德国云快递",
    "zhongwaiyun":"中外运速递",
    "zhuoshikuaiyun":"卓实快运",
    "ztong":"智通物流",
    "airgtc":"航空快递",
    "amazoncnorder":"亚马逊中国订单",
    "amusorder":"amazon-国际订单",
    "aplusex":"Aplus物流",
    "aus":"澳世速递",
    "bcwelt":"BCWELT",
    "bluedart":"BlueDart",
    "byht":"展勤快递",
    "chinatzx":"同舟行物流",
    "colombia":"哥伦比亚(4-72 La Red Postal de Colombia)",
    "dfkuaidi":"东风快递",
    "dhlpoland":"DHL-波兰（DHL Poland）",
    "edaeuexpress":"易达快运",
    "eshunda":"俄顺达",
    "euexpress":"EU-EXPRESS",
    "fedexuk":"FedEx-英国件（FedEx UK)",
    "gaotieex":"高铁快运",
    "gdxp":"新鹏快递",
    "ge2d":"GE2D跨境物流",
    "gswtkd":"万通快递",
    "haimengsudi":"海盟速递",
    "hhair56":"华瀚快递",
    "hnqst":"河南全速通",
    "jerseypost":"泽西岛",
    "jsexpress":"骏绅物流",
    "juwu":"聚物物流",
    "lqht":"恒通快递",
    "mauritius":"毛里求斯(Mauritius Post)",
    "mexico":"墨西哥（Correos de Mexico）",
    "milkyway":"银河物流",
    "nuoer":"诺尔国际物流",
    "polarisexpress":"北极星快运",
    "s2c":"S2C",
    "saiaodi":"赛澳递",
    "shunshid":"顺士达速运",
    "skynetmalaysia":"SkyNet Malaysia",
    "tdcargo":"TD Cargo",
    "tonghetianxia":"通和天下",
    "ubuy":"德国优拜物流",
    "vctrans":"越中国际物流",
    "wuyuansudi":"伍圆速递",
    "yhtlogistics":"宇航通物流",
    "yuandun":"远盾物流",
    "yuanhhk":"远航国际快运",
    "yyexp":"西安运逸快递",
    "zhongxinda":"忠信达",
    "adp":"ADP国际快递",
    "afghan":"阿富汗(Afghan Post)",
    "agopost":"全程快递",
    "ahkbps":"卡邦配送",
    "aosu":"澳速物流",
    "ariesfar":"艾瑞斯远",
    "aruba":"阿鲁巴[荷兰]（Post Aruba）",
    "campbellsexpress":"Campbell’s Express",
    "changyuwuliu":"长宇物流",
    "cnexps":"CNE",
    "csxss":"新时速物流",
    "cypruspost":"塞浦路斯(Cyprus Post)",
    "diantongkuaidi":"店通快递",
    "dpdpoland":"DPD Poland",
    "ecallturn":"E跨通",
    "egypt":"埃及（Egypt Post）",
    "fandaguoji":"颿达国际快递-英文",
    "fardarww":"颿达国际快递",
    "fedroad":"FedRoad 联邦转运",
    "feihukuaidi":"飞狐快递",
    "fenghuangkuaidi":"凤凰快递",
    "flysman":"飞力士物流",
    "gatikwe":"Gati-KWE",
    "gda":"安的快递",
    "gsm":"GSM",
    "gtongsudi":"广通速递",
    "gts":"GTS快递",
    "gttexpress":"GTT EXPRESS快递",
    "haoyoukuai":"好又快物流",
    "happylink":"开心快递",
    "hitaoe":"Hi淘易快递",
    "hkems":"云邮跨境快递",
    "hongbeixin":"红背心",
    "hongpinwuliu":"宏品物流",
    "hqtd":"环球通达 ",
    "hre":"高铁速递",
    "hsgtsd":"海硕高铁速递",
    "huada":"华达快运",
    "hutongwuliu":"户通物流",
    "hzpl":"华航快递",
    "idada":"大达物流",
    "iran":"伊朗（Iran Post）",
    "israelpost":"以色列(Israel Post)",
    "jiajiatong56":"佳家通货运",
    "jiguang":"极光转运",
    "jinyuekuaidi":"晋越快递",
    "kcs":"KCS",
    "krtao":"淘韩国际快递",
    "lanbiaokuaidi":"蓝镖快递",
    "letseml":"美联快递",
    "lgs":"lazada",
    "meitai":"美泰物流",
    "moldova":"摩尔多瓦(Posta Moldovei)",
    "mongolpost":"蒙古国(Mongol Post) ",
    "mrw":"MRW",
    "omniva":"爱沙尼亚(Eesti Post)",
    "pengcheng":"鹏程快递",
    "postdanmarken":"丹麦(Post Denmark)",
    "purolator":"Purolator",
    "qskdyxgs":"千顺快递",
    "quanchuan56":"全川物流",
    "quanxintong":"全信通快递",
    "safexpress":"Safexpress",
    "sfau":"澳丰速递",
    "sfift":"十方通物流",
    "sfpost":"曹操到",
    "shipsoho":"苏豪快递",
    "shiyunkuaidi":"世运快递",
    "sinoex":"中外运速递-中文",
    "siodemka":"Siodemka",
    "sofast56":"嗖一下同城快递",
    "staryvr":"星运快递",
    "supinexpress":"速品快递",
    "tianxiang":"天翔快递",
    "timedg":"万家通快递",
    "tollpriority":"Toll Priority(Toll Online)",
    "tunisia":"突尼斯EMS(Rapid-Poste)",
    "turtle":"海龟国际快递",
    "uex":"UEX国际物流",
    "ukraine":"乌克兰小包、大包(UkrPoshta)",
    "upsmailinno":"UPS Mail Innovations",
    "wenjiesudi":"文捷航空",
    "wotu":"渥途国际速运",
    "wtdex":"WTD海外通",
    "xsrd":"鑫世锐达",
    "yamaxunwuliu":"亚马逊中国",
    "yatfai":"一辉物流",
    "yifankd":"艺凡快递",
    "youlai":"邮来速递",
    "yourscm":"雅澳物流",
    "ytky168":"运通快运",
    "yuanzhijiecheng":"元智捷诚",
    "zhongjiwuliu":"中技物流",
    "adiexpress":"安达易国际速递",
    "afl":"AFL",
    "apgecommerce":"apgecommerce",
    "aplus100":"美国汉邦快递",
    "auex":"澳货通",
    "axexpress":"澳新物流",
    "azerbaijan":"阿塞拜疆EMS(EMS AzerExpressPost)",
    "bahrain":"巴林(Bahrain Post)",
    "bangladesh":"孟加拉国(EMS)",
    "baoxianda":"报通快递",
    "barbados":"巴巴多斯(Barbados Post)",
    "belize":"伯利兹(Belize Postal)",
    "belpost":"白俄罗斯(Belpochta)",
    "benniao":"笨鸟国际",
    "bester":"飛斯特",
    "bjqywl":"青云物流",
    "bjxsrd":"鑫锐达",
    "bmlchina":"标杆物流",
    "bohei":"波黑(JP BH Posta)",
    "bolivia":"玻利维亚",
    "borderguru":"BorderGuru",
    "botspost":"博茨瓦纳",
    "bphchina":"速方(Sufast)",
    "brunei":"文莱(Brunei Postal)",
    "caledonia":"新喀里多尼亚[法国](New Caledonia)",
    "cambodia":"柬埔寨(Cambodia Post)",
    "camekong":"到了港",
    "canhold":"能装能送",
    "canpar":"Canpar",
    "cargolux":"卢森堡航空",
    "cbo56":"钏博物流",
    "cdek":"CDEK",
    "chengda":"成达国际速递",
    "chengji":"城际快递",
    "chile":"智利(Correos Chile)",
    "chllog":"嘉荣物流",
    "chronopostfren":"法国大包、EMS-英文(Chronopost France)",
    "chronopostport":"Chronopost Portugal",
    "city56":"城市映急",
    "cjkoreaexpress":"大韩通运",
    "ckeex":"城晓国际快递",
    "clsp":"CL日中速运",
    "cnspeedster":"速舟物流",
    "cnup":"CNUP 中联邮",
    "correios":"莫桑比克（Correios de Moçambique）",
    "correoargentino":"阿根廷(Correo Argentina)",
    "correos":"哥斯达黎加(Correos de Costa Rica)",
    "cqxingcheng":"重庆星程快递",
    "czwlyn":"云南诚中物流",
    "dasu":"达速物流",
    "decnlh":"德中快递",
    "deltec":"Deltec Courier",
    "desworks":"澳行快递",
    "dfpost":"达方物流",
    "dhlhk":"DHL HK",
    "dhlnetherlands":"DHL-荷兰（DHL Netherlands）",
    "di5pll":"递五方云仓",
    "dianyi":"云南滇驿物流",
    "dingdong":"叮咚快递",
    "directlink":"Direct Link",
    "disifangau":"递四方澳洲",
    "disifangus":"递四方美国",
    "djy56":"天翔东捷运",
    "donghanwl":"东瀚物流",
    "donghong":"东红物流",
    "dpdgermany":"DPD Germany",
    "dtdcindia":"DTDC India",
    "ealceair":"东方航空物流",
    "ecfirstclass":"EC-Firstclass",
    "ecmsglobal":"ECMS Express",
    "ecuador":"厄瓜多尔(Correos del Ecuador)",
    "edragon":"龙象国际物流",
    "eiffel":"艾菲尔国际速递",
    "el56":"易联通达",
    "elta":"希腊包裹（ELTA Hellenic Post）",
    "eltahell":"希腊EMS（ELTA Courier）",
    "emirates":"阿联酋(Emirates Post)",
    "emsluqu":"高考通知书",
    "emssouthafrica":"南非EMS",
    "emsukraine":"乌克兰EMS(EMS Ukraine)",
    "emsukrainecn":"乌克兰EMS-中文(EMS Ukraine)",
    "england":"英国(大包,EMS)",
    "epspost":"联众国际",
    "est365":"东方汇",
    "estafeta":"Estafeta",
    "estes":"Estes",
    "ethiopia":"埃塞俄比亚(Ethiopian postal)",
    "eucnrail":"中欧国际物流",
    "europe8":"败欧洲",
    "eusacn":"优莎速运",
    "express7th":"7号速递",
    "expressplus":"澳洲新干线快递",
    "ezhuanyuan":"易转运",
    "fedexukcn":"FedEx-英国件",
    "fiji":"斐济(Fiji Post)",
    "flowerkd":"花瓣转运",
    "ftlexpress":"法翔速运",
    "gaticn":"Gati-中文",
    "gatien":"Gati-英文",
    "gdct56":"广东诚通物流",
    "gdqwwl":"全网物流",
    "gdrz58":"容智快运",
    "ghl":"环创物流",
    "gibraltar":"直布罗陀[英国]( Royal Gibraltar Post)",
    "gjwl":"冠捷物流 ",
    "globaltracktrace":"globaltracktrace",
    "gml":"英脉物流",
    "gotoubi":"UBI Australia",
    "greenland":"格陵兰[丹麦]（TELE Greenland A/S）",
    "grivertek":"潍鸿",
    "gscq365":"哥士传奇速递",
    "gtgogo":"GT国际快运",
    "guangdongtonglu":"广东通路",
    "guanting":"冠庭国际物流",
    "guosong":"国送快运",
    "gvpexpress":"宏观国际快递",
    "gzxingcheng":"贵州星程快递",
    "haihongmmb":"海红for买卖宝",
    "haiwaihuanqiu":"海外环球",
    "haixingqiao":"海星桥快递",
    "hangyu":"航宇快递",
    "haypost":"亚美尼亚(Haypost-Armenian Postal)",
    "hengrui56":"恒瑞物流",
    "highsince":"Highsince",
    "hlkytj":"互联快运",
    "hlpgyl":"共联配",
    "hmus":"华美快递",
    "hnfy":"飞鹰物流",
    "hnssd56":"顺时达物流",
    "homexpress":"居家通",
    "hongjie":"宏捷国际物流",
    "hrbzykd":"卓烨快递",
    "hrvatska":"克罗地亚（Hrvatska Posta）",
    "htwd":"华通务达物流",
    "huandonglg":"环东物流",
    "huiqiangkuaidi":"汇强快递",
    "humpline":"驼峰国际",
    "huoban":"兰州伙伴物流",
    "hyeship":"鸿远物流",
    "hyk":"上海昊宏国际货物",
    "iexpress":"iExpress",
    "ilogen":"logen路坚",
    "ilyang":"ILYANG",
    "imlb2c":"艾姆勒",
    "indonesia":"印度尼西亚EMS(Pos Indonesia-EMS)",
    "inposdom":"多米尼加（INPOSDOM – Instituto Postal Dominicano）",
    "interlink":"Interlink Express",
    "italysad":"Italy SDA",
    "jamaicapost":"牙买加（Jamaica Post）",
    "jdpplus":"急递",
    "jinchengwuliu":"锦程物流",
    "jintongkd":"劲通快递",
    "jiugong":"九宫物流",
    "jiuyicn":"久易快递",
    "jjx888":"佳捷翔物流",
    "jordan":"约旦(Jordan Post)",
    "juzhongda":"聚中大",
    "kaolaexpress":"考拉国际速递",
    "kazpost":"哈萨克斯坦(Kazpost)",
    "kenya":"肯尼亚(POSTA KENYA)",
    "koali":"番薯国际货运",
    "koreapostkr":"韩国邮政韩文",
    "kuaitao":"快淘快递",
    "kuaiyouda":"四川快优达速递",
    "kxda":"凯信达",
    "kyrgyzpost":"吉尔吉斯斯坦(Kyrgyz Post)",
    "kyue":"跨跃国际",
    "lanhukuaidi":"蓝弧快递",
    "lao":"老挝(Lao Express) ",
    "laposte":"塞内加尔",
    "lasy56":"林安物流",
    "lbbk":"立白宝凯物流",
    "ledii":"乐递供应链",
    "leopard":"云豹国际货运",
    "lesotho":"莱索托(Lesotho Post)",
    "lfexpress":"龙枫国际快递",
    "lianyun":"联运快递",
    "libanpost":"黎巴嫩(Liban Post)",
    "linex":"Linex",
    "lishi":"丽狮物流",
    "lithuania":"立陶宛（Lietuvos pa?tas）",
    "littlebearbear":"小熊物流",
    "lmfex":"良藤国际速递",
    "longfx":"龙飞祥快递",
    "longlangkuaidi":"隆浪快递",
    "longvast":"长风物流",
    "ltparcel":"联通快递",
    "lundao":"论道国际物流",
    "lwe":"LWE",
    "macedonia":"马其顿(Macedonian Post)",
    "mailikuaidi":"麦力快递",
    "mailongdy":"迈隆递运",
    "maldives":"马尔代夫(Maldives Post)",
    "malta":"马耳他（Malta Post）",
    "mangguo":"芒果速递",
    "mapleexpress":"今枫国际快运",
    "meibang":"美邦国际快递",
    "meidaexpress":"美达快递",
    "mexicodenda":"Mexico Senda Express",
    "mjexp":"美龙快递",
    "montenegro":"黑山(Posta Crne Gore)",
    "morocco":"摩洛哥 ( Morocco Post )",
    "mosuda":"魔速达",
    "multipack":"Mexico Multipack",
    "mxe56":"中俄速通（淼信）",
    "namibia":"纳米比亚(NamPost)",
    "nedahm":"红马速递",
    "nepalpost":"尼泊尔（Nepal Postal Services）",
    "nigerianpost":"尼日利亚(Nigerian Postal)",
    "njhaobo":"浩博物流",
    "nle":"NLE",
    "nlebv":"亚欧专线",
    "nmhuahe":"华赫物流",
    "novaposhta":"Nova Poshta",
    "ocaargen":"OCA Argentina",
    "oman":"阿曼(Oman Post)",
    "opek":"OPEK",
    "overseaex":"波音速递",
    "pakistan":"巴基斯坦(Pakistan Post)",
    "paraguay":"巴拉圭(Correo Paraguayo)",
    "pdstow":"全球速递",
    "peex":"派尔快递",
    "peisihuoyunkuaidi":"配思货运",
    "peixingwuliu":"陪行物流",
    "peru":"秘鲁(SERPOST)",
    "phlpost":"菲律宾（Philippine Postal）",
    "pinsuxinda":"品速心达快递",
    "pinxinkuaidi":"品信快递",
    "pioneer":"先锋国际快递",
    "portugalseur":"Portugal Seur",
    "postenab":"PostNord(Posten AB)",
    "postennorge":"挪威（Posten Norge）",
    "postpng":"巴布亚新几内亚(PNG Post)",
    "pzhjst":"急顺通",
    "qdants":"ANTS EXPRESS",
    "qhxykd":"雪域快递",
    "qianli":"千里速递",
    "qpost":"卡塔尔（Qatar Post）",
    "quansutong":"全速通",
    "quantium":"Quantium",
    "qzx56":"全之鑫物流",
    "redexpress":"Red Express",
    "rhtexpress":"睿和泰速运",
    "rokin":"荣庆物流",
    "romanian":"罗马尼亚（Posta Romanian）",
    "rpx":"rpx",
    "rwanda":"卢旺达(Rwanda i-posita)",
    "samoa":"萨摩亚(Samoa Post)",
    "sanshengco":"三盛快递",
    "scxingcheng":"四川星程快递",
    "sczpds":"速呈",
    "sdsy888":"首达速运",
    "selektvracht":"Selektvracht",
    "seur":"International Seur",
    "sfjhd":"圣飞捷快递",
    "shanda56":"衫达快运",
    "shanghaikuaitong":"上海快通",
    "shanghaiwujiangmmb":"上海无疆for买卖宝",
    "shaoke":"捎客物流",
    "shengtongscm":"盛通快递",
    "shenma":"神马快递",
    "shiningexpress":"阳光快递",
    "shipbyace":"王牌快递",
    "shpostwish":"wish邮",
    "shunbang":"顺邦国际物流",
    "sihaiet":"四海快递",
    "sihiexpress":"四海捷运",
    "sinoairinex":"中外运空运",
    "sixroad":"易普递",
    "skynet":"skynet",
    "skynetworldwide":"skynetworldwide",
    "skypost":"荷兰Sky Post",
    "slovak":"斯洛伐克(Slovenská Posta)",
    "slpost":"斯里兰卡(Sri Lanka Post)",
    "speeda":"行必达",
    "speedoex":"申必达",
    "staky":"首通快运",
    "starex":"星速递",
    "subaoex":"速豹",
    "sucheng":"速呈宅配",
    "sucmj":"特急便物流",
    "sudapost":"苏丹（Sudapost）",
    "suijiawuliu":"穗佳物流",
    "sujievip":"郑州速捷",
    "superoz":"速配欧翼",
    "taimek":"天美快递",
    "tanzania":"坦桑尼亚(Tanzania Posts)",
    "tcixps":"TCI XPS",
    "tianzong":"天纵物流",
    "tlky":"天联快运",
    "tntitaly":"TNT Italy",
    "tntpostcn":"TNT Post",
    "tny":"TNY物流",
    "tongdaxing":"通达兴物流",
    "topshey":"顶世国际物流",
    "uganda":"乌干达(Posta Uganda)",
    "ugoexpress":"邮鸽速运",
    "ukrpost":"乌克兰小包、大包(UkrPost)",
    "upsfreight":"UPS Freight",
    "utaoscm":"UTAO优到",
    "vanuatu":"瓦努阿图(Vanuatu Post)",
    "vietnam":"越南小包(Vietnam Posts)",
    "vipexpress":"鹰运国际速递",
    "wanjiatong":"宁夏万家通",
    "wdm":"万达美",
    "winit":"万邑通",
    "wlfast":"凡仕特物流",
    "wygj168":"万运国际快递",
    "wzhaunyun":"微转运",
    "xaetc":"西安胜峰",
    "xdshipping":"国晶物流",
    "xianchengliansudi":"西安城联速递",
    "xiangdawuliu":"湘达物流",
    "xiangteng":"翔腾物流",
    "xiaocex":"小C海淘",
    "xilaikd":"西安喜来快递",
    "xingyuankuaidi":"新元快递",
    "xyd666":"鑫远东速运",
    "ycgglobal":"YCG物流",
    "yemen":"也门(Yemen Post)",
    "yidihui":"驿递汇速递",
    "yihangmall":"易航物流",
    "yilingsuyun":"亿领速运",
    "yiqiguojiwuliu":"一柒国际物流",
    "yishunhang":"亿顺航",
    "yisong":"宜送",
    "yiyou":"易邮速运",
    "ykouan":"洋口岸",
    "yongbangwuliu":"永邦国际物流",
    "youjia":"友家速递",
    "ypsd":"壹品速递",
    "yuezhongsh":"粤中国际货运代理（上海）有限公司",
    "yufeng":"御风速运",
    "ywexpress":"远为快递",
    "zdepost":"直德邮",
    "zenzen":"三三国际物流",
    "zf365":"珠峰速运",
    "zhdwl":"众辉达物流",
    "zhitengwuliu":"志腾物流",
    "zhpex":"众派速递"
}
