export const SET_ORDERNO = 'SET_ORDERNO'

export const SET_SUBORDERNO = 'SET_SUBORDERNO'

export const SET_ORDERHOMEREFRESH = 'SET_ORDERHOMEREFRESH'

export const SET_ORDERTYPE = 'SET_ORDERTYPE'

export const SET_SERVICEID = 'SET_SERVICEID'

export const SET_HOMEREFRESH = 'SET_HOMEREFRESH'

export const SET_LOADING = 'SET_LOADING'

export const SET_SERVICESTATUS = 'SET_SERVICESTATUS'