# 设备信息
device:
  # 平台名称：是Android还是iOS
  platformName: Android
  # App平台原生自动化测试引擎
  automationName: UiAutomator2
  # 系统版本[只连接一台手机时可以不写，多台就要加上]
  platformVersion: '9'
  # 连接的设备名称
  deviceName: BGR6R19911003424
  # app的启动页面
  appActivity: com.sinosun.tchats.WiWelcomeActivity
  # 所测试的app包名
  appPackage: com.sinosun.bizmate.ace
  # Appium最新版本中noreset=false，意思是清除session信息，不会记录登录状态
  noReset: True
  chromedriverExecutableDir: D:\work projects\chrome_driver_H5
  # 支持输入中文
  unicodeKeyboard: True
  # 隐藏键盘
  resetKeyboard: True
  autoGrantPermissions: True

# API信息
sit_api:
  channelId: 9729
  companyId: d27c3129-a754-4278-90a6-92021a535b63
  uaId: 4462471022657@bizmatesit
  userId: 7b6d0861-f2db-42ba-be0c-e3450aa8a456
  url_token: https://bplussit.sinosun.com:18680/auth/realms/bplussit/protocol/openid-connect/token
  bbc_token_url: https://bplussit.sinosun.com:18380/mallbbc/v3/member/front/login/tokenExchange
  url_sit: https://bplussit.sinosun.com:18380/